image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build-image:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:v1 .
    - docker push $CI_REGISTRY_IMAGE:v1
